"""empty message

Revision ID: cc2856714211
Revises: 
Create Date: 2023-03-07 08:54:30.779296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc2856714211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.alter_column('date_posted',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_constraint('blog_post_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_blog_post_poster_id_users'), 'users', ['poster_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.drop_constraint('comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_username_users'), 'users', ['username'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('likes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_likes_username_users'), 'users', ['username'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_likes_username_users'), type_='foreignkey')
        batch_op.create_foreign_key('likes_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_column('date_posted')
        batch_op.drop_column('username')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comments_username_users'), type_='foreignkey')
        batch_op.create_foreign_key('comments_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('date_posted',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('content',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('username')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_blog_post_poster_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('blog_post_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.String(length=256),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
