"""empty message

Revision ID: f18777f0ee00
Revises: 
Create Date: 2023-03-16 16:35:49.774607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f18777f0ee00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_constraint('blog_post_ibfk_2', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('comments_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('likes_ibfk_4', type_='foreignkey')
        batch_op.drop_column('poster_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('poster_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('likes_ibfk_4', 'blog_post', ['poster_id'], ['id'])
        batch_op.create_foreign_key('likes_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comments_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('blog_post_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.String(length=256),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###
